In [1]:
# a에 type이 int인 1을 assign함. 
a = 1; print(type(a))

<class 'int'>


In [2]:
# 1의 type은 int고, 1.0의 type은 float임. 
a = 1; a = float(a); print(type(a))

<class 'float'>


In [3]:
# 1의 type은 float인데, int로 바꾸면 1임. 
a = 1.2; a = int(a); print(type(a))

<class 'int'>


In [4]:
# string이라는 문자열 데이터의 순서.... [0]이 첫번째고, [1]이 두번째다. 
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


In [5]:
#문자열 데이터를 list화 시키는 과정이다. 'abc'를 list화하면 ['a','b','c']가 된다. 
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


In [6]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


In [7]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


In [8]:
# Dict...
a = {"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


In [28]:
# tuple과 list를 자유자재로 사용할 수 있어야 한다. 
a=[(1,2,3), (3,8,0)]
print(type(a))
print(a)
print(type(a[0]))
print(a[0][0])

<class 'list'>
[(1, 2, 3), (3, 8, 0)]
<class 'tuple'>
1


In [10]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


In [11]:
# 원래 곱해지면 안되는데, 곱해짐. 따라서, np.array는 행렬이 아니다. 
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


In [13]:
# np.matrix 은 행렬임. 
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [14]:
# 곱해지지 않는다. 행렬의 곱셈...
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [16]:
c*c.T

matrix([[14, 19],
        [19, 73]])